export default {
  container: {
    width: '98%',
    margin: '1%',
    marginBottom: 0,
  },
  content: {
    margin: 8,
    padding: 8,
    boxShadow: '0 8px 16px rgba(4, 172, 167, 0.16), 0 0 2px rgba(4, 172, 167, 0.16)',
    borderRadius: 6,
  },
  ownNavTabs: {
    justifyContent: 'center',
    display: 'flex',
    flexDirection: 'row',
    marginBottom: 24,
  },
  ownNavLink: {
    padding: 8,
    height: 48,
    minWidth: 128,
    justifyContent: 'center',
    borderBottomWidth: 3,
    borderBottomColor: '#F5F6F7',
  },
  ownNavLinkActive: {
    fontWeight: 'bold',
    fontSize: 14,
    textAlign: 'center',
    color: '#0070F2',
    borderBottomColor: '#0070F2',
  },
  ownNavLinkNonActive: {
    fontWeight: 'bold',
    fontSize: 14,
    textAlign: 'center',
  },
  ownInput: {
    borderWidth: 1,
    borderColor: 'transparent',
    borderRadius: 6,
    height: 48,
    padding: 0,
    paddingLeft: 11,
    paddingRight: 11,
    marginBottom: 8,
  },
  row: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  buttonContainer: {
    elevation: 8,
    backgroundColor: "#0070F2",
    borderRadius: 4,
    padding: 10,
    marginTop: 8,
    marginBottom: 16,
  },
  buttonText: {
    fontSize: 16,
    color: "#fff",
    fontWeight: "bold",
    alignSelf: "center",
  },
  loader: {
    position: 'absolute',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'transparent',
  },
  errors: {
    color: '#B00020',
    fontSize: 14,
    marginTop: 16,
    margin: 8,
  },
  profileTitle: {
    textAlign: 'center',
    alignItems: 'center',
    fontSize: 18,
    lineHeight: 20,
    fontWeight: 'bold',
    marginTop: 16,
    paddingBottom: 20,
  },
  profile: {
    padding: 8,
    fontSize: 14,
    fontWeight: 'normal',
  },
};
